### PR TITLE
Add create-vms.sh script with a short readme.

### PR DESCRIPTION
**Pull request by fodurrr**
Simple script to create multiple Virtual Machines automatically

1. It will ask you some questions about your wished Virtual Machines.
    - You can select Debian or Ubuntu image
2. Prints a detailed info with about the VMs going to be created.
3. Let you confirm if You want to continue
4. You can chose to start all VMs at the end 🚀

### CODE REVIEW

**Comment by JamesTurland** [comment]
This looks great, thanks. I will test and report back.

**Comment by KimVatnedal** [comment]
Is it possible to also add the use of local templates? many have customized local templates that they use to create their VM's..?

**Comment by fodurrr** [comment]
> Is it possible to also add the use of local templates? many have customized local templates that they use to create their VM's..?

Can you elaborate what you mean on local templates? I was thinking to move all default variables into a separated file then it can basically act as a template. Or what kind of template file you mean?

**Comment by KimVatnedal** [comment]
> > Is it possible to also add the use of local templates? many have customized local templates that they use to create their VM's..?
> 
> Can you elaborate what you mean on local templates, proxmox templates? I was thinking to move all default variables into a separated file then it can basically act as a template. Or what kind of template file you mean?

I have a separate script that downloads images and prepares them as templates, with preinstalled docker etc. So instead of downloading images, is it possible to use existing templates of vms?

**Pull request merged**
